-- CREATE TABLE Employee (
--     Ename VARCHAR(255),
--     Eid INT PRIMARY KEY,
--     Edept VARCHAR(255),
--     Edob DATE,
--     Egender VARCHAR(10),
--     Edesign VARCHAR(255),
--     Esalary DECIMAL(10,2),
--     Eaddress VARCHAR(255),
--     Elocation VARCHAR(255),
--     Epincode INT,
--     Eexperience INT,
--     Eage INT
-- );
